apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: dGVzdGRi        # base64 encoded 'testdb'
  POSTGRES_USER: YWRtaW4=      # base64 encoded 'admin'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 encoded 'password'
