apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "my-backend.fullname" . } }
  labels:
    app: { { include "my-backend.name" . } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { include "my-backend.name" . } }
  template:
    metadata:
      labels:
        app: { { include "my-backend.name" . } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: { { .Values.image.pullPolicy } }
          env:
            - name: DB_HOST
              value: { { .Values.db.host | quote } }
            - name: DB_PORT
              value: { { .Values.db.port | quote } }
            - name: DB_NAME
              value: { { .Values.db.name | quote } }
            - name: DB_USER
              value: { { .Values.db.user | quote } }
            - name: DB_PASSWORD
              value: { { .Values.db.password | quote } }
          ports:
            - containerPort: 8080
          resources: { { - toYaml .Values.resources | nindent 12 } }
