apiVersion: v1
kind: Secret
metadata:
  name: { { .Values.postgres.secretName } }
type: Opaque
data:
  POSTGRES_DB: { { .Values.postgres.db | b64enc | quote } }
  POSTGRES_USER: { { .Values.postgres.user | b64enc | quote } }
  POSTGRES_PASSWORD: { { .Values.postgres.password | b64enc | quote } }
